-- ============================================================================
-- 006 MAINTENANCE: condition reports, maintenance records, tooling requests
-- ============================================================================

CREATE TABLE tooling_damage_reports (
  id INT AUTO_INCREMENT PRIMARY KEY,
  report_no VARCHAR(40) NOT NULL UNIQUE,
  tooling_item_id INT NOT NULL,
  damage_type VARCHAR(30) NOT NULL,
  severity VARCHAR(20) NOT NULL DEFAULT 'MEDIUM',
  location_note VARCHAR(255) NULL,
  description TEXT NULL,
  production_order_id INT NULL,
  reported_by INT NULL,
  reported_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  status VARCHAR(20) NOT NULL DEFAULT 'OPEN',
  maintenance_id INT NULL,
  resolved_at DATETIME NULL,
  resolution VARCHAR(500) NULL,
  photos_created TINYINT(1) NOT NULL DEFAULT 0,
  image_ids TEXT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT dmg_tool_fk FOREIGN KEY (tooling_item_id) REFERENCES tooling_items (id) ON DELETE CASCADE,
  CONSTRAINT dmg_user_fk FOREIGN KEY (reported_by) REFERENCES users (id) ON DELETE SET NULL,
  INDEX idx_dmg_status (status, severity),
  INDEX idx_dmg_tool (tooling_item_id, reported_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE tooling_maintenance (
  id INT AUTO_INCREMENT PRIMARY KEY,
  tooling_item_id INT NOT NULL,
  kind VARCHAR(20) NOT NULL DEFAULT 'PREVENTIVE',
  status VARCHAR(20) NOT NULL DEFAULT 'SCHEDULED',
  priority VARCHAR(10) NOT NULL DEFAULT 'NORMAL',
  scheduled_date DATE NULL,
  completed_date DATE NULL,
  technician VARCHAR(120) NULL,
  work_description TEXT NULL,
  findings TEXT NULL,
  condition_before VARCHAR(20) NULL,
  condition_after VARCHAR(20) NULL,
  parts_replaced VARCHAR(400) NULL,
  cost DECIMAL(12,2) NULL,
  downtime_hours DECIMAL(8,2) NULL,
  next_maintenance_date DATE NULL,
  before_image_ids VARCHAR(255) NULL,
  after_image_ids VARCHAR(255) NULL,
  damage_report_id INT NULL,
  created_by INT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  CONSTRAINT maint_tool_fk FOREIGN KEY (tooling_item_id) REFERENCES tooling_items (id) ON DELETE CASCADE,
  CONSTRAINT maint_dmg_fk FOREIGN KEY (damage_report_id) REFERENCES tooling_damage_reports (id) ON DELETE SET NULL,
  CONSTRAINT maint_user_fk FOREIGN KEY (created_by) REFERENCES users (id) ON DELETE SET NULL,
  INDEX idx_maint_tool (tooling_item_id, status),
  INDEX idx_maint_due (status, scheduled_date)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE tooling_requests (
  id INT AUTO_INCREMENT PRIMARY KEY,
  request_no VARCHAR(40) NOT NULL UNIQUE,
  filter_id INT NULL,
  requested_tooling_type_id INT NULL,
  title VARCHAR(200) NOT NULL,
  description TEXT NULL,
  priority VARCHAR(10) NOT NULL DEFAULT 'NORMAL',
  status VARCHAR(20) NOT NULL DEFAULT 'PENDING',
  quantity INT NOT NULL DEFAULT 1,
  target_date DATE NULL,
  requested_by INT NULL,
  requested_for_dept VARCHAR(60) NULL,
  assigned_to INT NULL,
  approved_by INT NULL,
  approved_at DATETIME NULL,
  rejection_reason VARCHAR(400) NULL,
  existing_tool_id INT NULL,
  created_tooling_id INT NULL,
  checked_existing TINYINT(1) NOT NULL DEFAULT 0,
  estimate_cost DECIMAL(12,2) NULL,
  actual_cost DECIMAL(12,2) NULL,
  completed_at DATETIME NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  CONSTRAINT req_filter_fk FOREIGN KEY (filter_id) REFERENCES filters (id) ON DELETE SET NULL,
  CONSTRAINT req_type_fk FOREIGN KEY (requested_tooling_type_id) REFERENCES tooling_types (id) ON DELETE SET NULL,
  CONSTRAINT req_user_fk FOREIGN KEY (requested_by) REFERENCES users (id) ON DELETE SET NULL,
  CONSTRAINT req_assignee_fk FOREIGN KEY (assigned_to) REFERENCES users (id) ON DELETE SET NULL,
  CONSTRAINT req_tool_fk FOREIGN KEY (created_tooling_id) REFERENCES tooling_items (id) ON DELETE SET NULL,
  INDEX idx_req_status (status, priority, target_date),
  INDEX idx_req_filter (filter_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
