/** Header text -> import field keys (shared by the CSV + XLSX import paths). */
export const HEADER_ALIASES = {
  internal_number: ['internal number', 'internal_number', 'number', 'part number'],
  product_number: ['product number', 'product_number', 'catalogue number'],
  name: ['name', 'description'],
  filter_type: ['filter type', 'type'],
  brand: ['brand', 'make'],
  length_mm: ['length (mm)', 'length_mm', 'length'],
  width_mm: ['width (mm)', 'width_mm', 'width'],
  height_mm: ['height (mm)', 'height_mm', 'height'],
  outer_diameter_mm: ['outer diameter (mm)', 'outer_diameter_mm', 'diameter'],
  status: ['status'],
  oem_numbers: ['oem numbers', 'oem', 'cross references'],
  tooling_id: ['tooling id', 'tooling_id', 'code'],
  tooling_type: ['category', 'tooling type', 'type'],
  condition_rating: ['condition', 'condition_rating'],
  quantity: ['quantity', 'qty'],
  material: ['material'],
  max_cycles: ['max cycles', 'max_cycles'],
  location: ['location code', 'location'],
  filter_number: ['used for filter', 'filter number', 'filter'],
  manufacturer: ['manufacturer', 'make'],
  model: ['model'],
  generation: ['generation'],
  year_from: ['year from', 'year_from'],
  year_to: ['year to', 'year_to'],
  engine: ['engine'],
  engine_code: ['engine code', 'engine_code'],
  fuel: ['fuel', 'fuel type'],
  power_hp: ['power (hp)', 'power_hp', 'power'],
  quantity_per_vehicle: ['qty per vehicle', 'quantity_per_vehicle'],
  overall_length_mm: ['length (mm)', 'overall_length_mm'],
  overall_width_mm: ['width (mm)', 'overall_width_mm'],
  overall_height_mm: ['height (mm)', 'overall_height_mm'],
};

